language: go

go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_AUTH_SECRET
  keep_history: true
  on:
    branch: master
